server:
  port: 7070
  servlet:
    context-path: /ticket
  error:
    include-message: always
spring:
  application:
    name: ticket-service
  mvc:
    servlet:
      path: /api/v1
  datasource:
    username: user
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_ticket
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7970/eureka
    fetch-registry: true
    register-with-eureka: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
