version: '3.1'
services:
  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
  elasticsearch:
    image: elasticsearch:8.1.1
    container_name: elasticsearch_training
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
  mysql:
    container_name: db_ticket
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ticket
    ports:
      - "3306:3306"